<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:pfx0="http://www.tibco.com/schemas/Davivienda_Transactions_HCS/Hybrid_Card_Davivienda.Core/Validations/Get_Validations_FromFCS/Contingencias/Schema.xsd" xmlns:pfx1="http://www.tibco.com/schemas/Davivienda_Transactions_HCS/Hybrid_Card_Davivienda.Core/Validations/Get_Validations_FromFCS/Contingencias/Schema.xsd2" xmlns:tns="http://www.recaudobogota.com.co/Contingencias" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.recaudobogota.com.co/Contingencias">
    <import namespace="http://www.tibco.com/schemas/Davivienda_Transactions_HCS/Hybrid_Card_Davivienda.Core/Validations/Get_Validations_FromFCS/Contingencias/Schema.xsd" location="../ContingenciasIN.xsd"/>
    <import namespace="http://www.tibco.com/schemas/Davivienda_Transactions_HCS/Hybrid_Card_Davivienda.Core/Validations/Get_Validations_FromFCS/Contingencias/Schema.xsd2" location="../ContingenciasOUT.xsd"/>
    <message name="Contingencias">
        <part element="pfx0:Contingencias" name="parameters"/>
    </message>
    <message name="Contingencias2">
        <part element="pfx1:Contingencias" name="parameters"/>
    </message>
    <portType name="ContingenciasUsos">
        <operation name="ContingenciasMainOp">
            <input message="tns:Contingencias"/>
            <output message="tns:Contingencias2"/>
        </operation>
    </portType>
</definitions>